import { MigrationInterface, QueryRunner } from "typeorm";

export class ChannelsToMidiFiles1784119855075 implements MigrationInterface {
    name = 'ChannelsToMidiFiles1784119855075'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_PlaylistSong" ("id" integer PRIMARY KEY, "idx" integer, "playlist_id" integer, "song_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "temporary_PlaylistSong" RENAME TO "PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "temporary_CoilEvent" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "atMs" integer NOT NULL, "param" text NOT NULL, "value" real NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_CoilEvent"("id", "song_id", "coilIndex", "atMs", "param", "value") SELECT "id", "song_id", "coilIndex", "atMs", "param", "value" FROM "CoilEvent"`);
        await queryRunner.query(`DROP TABLE "CoilEvent"`);
        await queryRunner.query(`ALTER TABLE "temporary_CoilEvent" RENAME TO "CoilEvent"`);
        await queryRunner.query(`DROP INDEX "UQ_song_uuid"`);
        await queryRunner.query(`CREATE TABLE "temporary_Song" ("id" integer PRIMARY KEY, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "Song"`);
        await queryRunner.query(`DROP TABLE "Song"`);
        await queryRunner.query(`ALTER TABLE "temporary_Song" RENAME TO "Song"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_song_uuid" ON "Song" ("uuid") WHERE uuid IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "temporary_Coil" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0), CONSTRAINT "UQ_25f7b29e8c1c5ea083dd7201d09" UNIQUE ("song_id", "coilIndex"))`);
        await queryRunner.query(`INSERT INTO "temporary_Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "Coil"`);
        await queryRunner.query(`DROP TABLE "Coil"`);
        await queryRunner.query(`ALTER TABLE "temporary_Coil" RENAME TO "Coil"`);
        await queryRunner.query(`DROP INDEX "UQ_midifile_uuid"`);
        await queryRunner.query(`DROP INDEX "UQ_playlist_uuid"`);
        await queryRunner.query(`DROP INDEX "UQ_song_uuid"`);
        await queryRunner.query(`CREATE TABLE "temporary_Coil" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "Coil"`);
        await queryRunner.query(`DROP TABLE "Coil"`);
        await queryRunner.query(`ALTER TABLE "temporary_Coil" RENAME TO "Coil"`);
        await queryRunner.query(`CREATE TABLE "temporary_MidiFile" ("id" integer PRIMARY KEY, "name" text, "path" text, "durationMs" integer, "channels" integer, "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_MidiFile"("id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName" FROM "MidiFile"`);
        await queryRunner.query(`DROP TABLE "MidiFile"`);
        await queryRunner.query(`ALTER TABLE "temporary_MidiFile" RENAME TO "MidiFile"`);
        await queryRunner.query(`CREATE TABLE "temporary_Playlist" ("id" integer PRIMARY KEY, "name" text, "coilCount" integer NOT NULL DEFAULT (3), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_Playlist"("id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName" FROM "Playlist"`);
        await queryRunner.query(`DROP TABLE "Playlist"`);
        await queryRunner.query(`ALTER TABLE "temporary_Playlist" RENAME TO "Playlist"`);
        await queryRunner.query(`CREATE TABLE "temporary_PlaylistSong" ("id" integer PRIMARY KEY, "idx" integer, "playlist_id" integer, "song_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "temporary_PlaylistSong" RENAME TO "PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "temporary_AppConfig" ("id" integer PRIMARY KEY, "coilNames" text, "defaultCoilCount" integer NOT NULL DEFAULT (3))`);
        await queryRunner.query(`INSERT INTO "temporary_AppConfig"("id", "coilNames", "defaultCoilCount") SELECT "id", "coilNames", "defaultCoilCount" FROM "AppConfig"`);
        await queryRunner.query(`DROP TABLE "AppConfig"`);
        await queryRunner.query(`ALTER TABLE "temporary_AppConfig" RENAME TO "AppConfig"`);
        await queryRunner.query(`CREATE TABLE "temporary_Song" ("id" integer PRIMARY KEY, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "Song"`);
        await queryRunner.query(`DROP TABLE "Song"`);
        await queryRunner.query(`ALTER TABLE "temporary_Song" RENAME TO "Song"`);
        await queryRunner.query(`CREATE TABLE "temporary_MidiFile" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text, "path" text, "durationMs" integer, "channels" integer, "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_MidiFile"("id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName" FROM "MidiFile"`);
        await queryRunner.query(`DROP TABLE "MidiFile"`);
        await queryRunner.query(`ALTER TABLE "temporary_MidiFile" RENAME TO "MidiFile"`);
        await queryRunner.query(`CREATE TABLE "temporary_Playlist" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" text, "coilCount" integer NOT NULL DEFAULT (3), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_Playlist"("id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName" FROM "Playlist"`);
        await queryRunner.query(`DROP TABLE "Playlist"`);
        await queryRunner.query(`ALTER TABLE "temporary_Playlist" RENAME TO "Playlist"`);
        await queryRunner.query(`CREATE TABLE "temporary_PlaylistSong" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "idx" integer, "playlist_id" integer, "song_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "temporary_PlaylistSong" RENAME TO "PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "temporary_AppConfig" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "coilNames" text, "defaultCoilCount" integer NOT NULL DEFAULT (3))`);
        await queryRunner.query(`INSERT INTO "temporary_AppConfig"("id", "coilNames", "defaultCoilCount") SELECT "id", "coilNames", "defaultCoilCount" FROM "AppConfig"`);
        await queryRunner.query(`DROP TABLE "AppConfig"`);
        await queryRunner.query(`ALTER TABLE "temporary_AppConfig" RENAME TO "AppConfig"`);
        await queryRunner.query(`CREATE TABLE "temporary_CoilEvent" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "atMs" integer NOT NULL, "param" text NOT NULL, "value" real NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_CoilEvent"("id", "song_id", "coilIndex", "atMs", "param", "value") SELECT "id", "song_id", "coilIndex", "atMs", "param", "value" FROM "CoilEvent"`);
        await queryRunner.query(`DROP TABLE "CoilEvent"`);
        await queryRunner.query(`ALTER TABLE "temporary_CoilEvent" RENAME TO "CoilEvent"`);
        await queryRunner.query(`CREATE TABLE "temporary_Song" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "temporary_Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "Song"`);
        await queryRunner.query(`DROP TABLE "Song"`);
        await queryRunner.query(`ALTER TABLE "temporary_Song" RENAME TO "Song"`);
        await queryRunner.query(`CREATE TABLE "temporary_Coil" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "Coil"`);
        await queryRunner.query(`DROP TABLE "Coil"`);
        await queryRunner.query(`ALTER TABLE "temporary_Coil" RENAME TO "Coil"`);
        await queryRunner.query(`CREATE TABLE "temporary_Coil" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0), CONSTRAINT "UQ_coil_song_index" UNIQUE ("song_id", "coilIndex"))`);
        await queryRunner.query(`INSERT INTO "temporary_Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "Coil"`);
        await queryRunner.query(`DROP TABLE "Coil"`);
        await queryRunner.query(`ALTER TABLE "temporary_Coil" RENAME TO "Coil"`);
        await queryRunner.query(`CREATE TABLE "temporary_PlaylistSong" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "idx" integer, "playlist_id" integer, "song_id" integer, CONSTRAINT "FK_88fd2840d87fbbf507316f08a8d" FOREIGN KEY ("playlist_id") REFERENCES "Playlist" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "temporary_PlaylistSong" RENAME TO "PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "temporary_CoilEvent" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "atMs" integer NOT NULL, "param" text NOT NULL, "value" real NOT NULL, CONSTRAINT "FK_8b7f3f0567e0c3f80bb83513218" FOREIGN KEY ("song_id") REFERENCES "Song" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_CoilEvent"("id", "song_id", "coilIndex", "atMs", "param", "value") SELECT "id", "song_id", "coilIndex", "atMs", "param", "value" FROM "CoilEvent"`);
        await queryRunner.query(`DROP TABLE "CoilEvent"`);
        await queryRunner.query(`ALTER TABLE "temporary_CoilEvent" RENAME TO "CoilEvent"`);
        await queryRunner.query(`CREATE TABLE "temporary_Song" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text, CONSTRAINT "FK_836e600ff46bf5103819050cc43" FOREIGN KEY ("midiFile_id") REFERENCES "MidiFile" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "Song"`);
        await queryRunner.query(`DROP TABLE "Song"`);
        await queryRunner.query(`ALTER TABLE "temporary_Song" RENAME TO "Song"`);
        await queryRunner.query(`CREATE TABLE "temporary_Coil" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0), CONSTRAINT "UQ_coil_song_index" UNIQUE ("song_id", "coilIndex"), CONSTRAINT "FK_5e68da09ebe34b54efa88c52168" FOREIGN KEY ("song_id") REFERENCES "Song" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "Coil"`);
        await queryRunner.query(`DROP TABLE "Coil"`);
        await queryRunner.query(`ALTER TABLE "temporary_Coil" RENAME TO "Coil"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Coil" RENAME TO "temporary_Coil"`);
        await queryRunner.query(`CREATE TABLE "Coil" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0), CONSTRAINT "UQ_coil_song_index" UNIQUE ("song_id", "coilIndex"))`);
        await queryRunner.query(`INSERT INTO "Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "temporary_Coil"`);
        await queryRunner.query(`DROP TABLE "temporary_Coil"`);
        await queryRunner.query(`ALTER TABLE "Song" RENAME TO "temporary_Song"`);
        await queryRunner.query(`CREATE TABLE "Song" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_Song"`);
        await queryRunner.query(`DROP TABLE "temporary_Song"`);
        await queryRunner.query(`ALTER TABLE "CoilEvent" RENAME TO "temporary_CoilEvent"`);
        await queryRunner.query(`CREATE TABLE "CoilEvent" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "atMs" integer NOT NULL, "param" text NOT NULL, "value" real NOT NULL)`);
        await queryRunner.query(`INSERT INTO "CoilEvent"("id", "song_id", "coilIndex", "atMs", "param", "value") SELECT "id", "song_id", "coilIndex", "atMs", "param", "value" FROM "temporary_CoilEvent"`);
        await queryRunner.query(`DROP TABLE "temporary_CoilEvent"`);
        await queryRunner.query(`ALTER TABLE "PlaylistSong" RENAME TO "temporary_PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "PlaylistSong" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "idx" integer, "playlist_id" integer, "song_id" integer)`);
        await queryRunner.query(`INSERT INTO "PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "temporary_PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "temporary_PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "Coil" RENAME TO "temporary_Coil"`);
        await queryRunner.query(`CREATE TABLE "Coil" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "song_id" integer, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "temporary_Coil"`);
        await queryRunner.query(`DROP TABLE "temporary_Coil"`);
        await queryRunner.query(`ALTER TABLE "Coil" RENAME TO "temporary_Coil"`);
        await queryRunner.query(`CREATE TABLE "Coil" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "temporary_Coil"`);
        await queryRunner.query(`DROP TABLE "temporary_Coil"`);
        await queryRunner.query(`ALTER TABLE "Song" RENAME TO "temporary_Song"`);
        await queryRunner.query(`CREATE TABLE "Song" ("id" integer PRIMARY KEY, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_Song"`);
        await queryRunner.query(`DROP TABLE "temporary_Song"`);
        await queryRunner.query(`ALTER TABLE "CoilEvent" RENAME TO "temporary_CoilEvent"`);
        await queryRunner.query(`CREATE TABLE "CoilEvent" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "atMs" integer NOT NULL, "param" text NOT NULL, "value" real NOT NULL)`);
        await queryRunner.query(`INSERT INTO "CoilEvent"("id", "song_id", "coilIndex", "atMs", "param", "value") SELECT "id", "song_id", "coilIndex", "atMs", "param", "value" FROM "temporary_CoilEvent"`);
        await queryRunner.query(`DROP TABLE "temporary_CoilEvent"`);
        await queryRunner.query(`ALTER TABLE "AppConfig" RENAME TO "temporary_AppConfig"`);
        await queryRunner.query(`CREATE TABLE "AppConfig" ("id" integer PRIMARY KEY, "coilNames" text, "defaultCoilCount" integer NOT NULL DEFAULT (3))`);
        await queryRunner.query(`INSERT INTO "AppConfig"("id", "coilNames", "defaultCoilCount") SELECT "id", "coilNames", "defaultCoilCount" FROM "temporary_AppConfig"`);
        await queryRunner.query(`DROP TABLE "temporary_AppConfig"`);
        await queryRunner.query(`ALTER TABLE "PlaylistSong" RENAME TO "temporary_PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "PlaylistSong" ("id" integer PRIMARY KEY, "idx" integer, "playlist_id" integer, "song_id" integer)`);
        await queryRunner.query(`INSERT INTO "PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "temporary_PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "temporary_PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "Playlist" RENAME TO "temporary_Playlist"`);
        await queryRunner.query(`CREATE TABLE "Playlist" ("id" integer PRIMARY KEY, "name" text, "coilCount" integer NOT NULL DEFAULT (3), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "Playlist"("id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_Playlist"`);
        await queryRunner.query(`DROP TABLE "temporary_Playlist"`);
        await queryRunner.query(`ALTER TABLE "MidiFile" RENAME TO "temporary_MidiFile"`);
        await queryRunner.query(`CREATE TABLE "MidiFile" ("id" integer PRIMARY KEY, "name" text, "path" text, "durationMs" integer, "channels" integer, "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "MidiFile"("id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_MidiFile"`);
        await queryRunner.query(`DROP TABLE "temporary_MidiFile"`);
        await queryRunner.query(`ALTER TABLE "Song" RENAME TO "temporary_Song"`);
        await queryRunner.query(`CREATE TABLE "Song" ("id" integer PRIMARY KEY, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_Song"`);
        await queryRunner.query(`DROP TABLE "temporary_Song"`);
        await queryRunner.query(`ALTER TABLE "AppConfig" RENAME TO "temporary_AppConfig"`);
        await queryRunner.query(`CREATE TABLE "AppConfig" ("id" integer PRIMARY KEY, "coilNames" text, "defaultCoilCount" integer NOT NULL DEFAULT (3))`);
        await queryRunner.query(`INSERT INTO "AppConfig"("id", "coilNames", "defaultCoilCount") SELECT "id", "coilNames", "defaultCoilCount" FROM "temporary_AppConfig"`);
        await queryRunner.query(`DROP TABLE "temporary_AppConfig"`);
        await queryRunner.query(`ALTER TABLE "PlaylistSong" RENAME TO "temporary_PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "PlaylistSong" ("id" integer PRIMARY KEY, "idx" integer, "playlist_id" integer, "song_id" integer)`);
        await queryRunner.query(`INSERT INTO "PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "temporary_PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "temporary_PlaylistSong"`);
        await queryRunner.query(`ALTER TABLE "Playlist" RENAME TO "temporary_Playlist"`);
        await queryRunner.query(`CREATE TABLE "Playlist" ("id" integer PRIMARY KEY, "name" text, "coilCount" integer NOT NULL DEFAULT (3), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "Playlist"("id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "coilCount", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_Playlist"`);
        await queryRunner.query(`DROP TABLE "temporary_Playlist"`);
        await queryRunner.query(`ALTER TABLE "MidiFile" RENAME TO "temporary_MidiFile"`);
        await queryRunner.query(`CREATE TABLE "MidiFile" ("id" integer PRIMARY KEY, "name" text, "path" text, "durationMs" integer, "channels" integer, "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text)`);
        await queryRunner.query(`INSERT INTO "MidiFile"("id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "name", "path", "durationMs", "channels", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_MidiFile"`);
        await queryRunner.query(`DROP TABLE "temporary_MidiFile"`);
        await queryRunner.query(`ALTER TABLE "Coil" RENAME TO "temporary_Coil"`);
        await queryRunner.query(`CREATE TABLE "Coil" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0), CONSTRAINT "UQ_25f7b29e8c1c5ea083dd7201d09" UNIQUE ("song_id", "coilIndex"))`);
        await queryRunner.query(`INSERT INTO "Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "temporary_Coil"`);
        await queryRunner.query(`DROP TABLE "temporary_Coil"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_song_uuid" ON "Song" ("uuid") WHERE uuid IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_playlist_uuid" ON "Playlist" ("uuid") WHERE uuid IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_midifile_uuid" ON "MidiFile" ("uuid") WHERE uuid IS NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Coil" RENAME TO "temporary_Coil"`);
        await queryRunner.query(`CREATE TABLE "Coil" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "channelMask" integer NOT NULL DEFAULT (0), "ontimeUs" integer NOT NULL DEFAULT (0), "duty" real NOT NULL DEFAULT (0), CONSTRAINT "UQ_25f7b29e8c1c5ea083dd7201d09" UNIQUE ("song_id", "coilIndex"), CONSTRAINT "FK_5e68da09ebe34b54efa88c52168" FOREIGN KEY ("song_id") REFERENCES "Song" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "Coil"("id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty") SELECT "id", "song_id", "coilIndex", "channelMask", "ontimeUs", "duty" FROM "temporary_Coil"`);
        await queryRunner.query(`DROP TABLE "temporary_Coil"`);
        await queryRunner.query(`DROP INDEX "UQ_song_uuid"`);
        await queryRunner.query(`ALTER TABLE "Song" RENAME TO "temporary_Song"`);
        await queryRunner.query(`CREATE TABLE "Song" ("id" integer PRIMARY KEY, "midiFile_id" integer, "name" text, "coilCount" integer NOT NULL DEFAULT (1), "mode" text NOT NULL DEFAULT ('midi'), "output2Mask" integer NOT NULL DEFAULT (0), "uuid" text, "updatedAt" integer, "contentHash" text, "editorName" text, CONSTRAINT "FK_836e600ff46bf5103819050cc43" FOREIGN KEY ("midiFile_id") REFERENCES "MidiFile" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "Song"("id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName") SELECT "id", "midiFile_id", "name", "coilCount", "mode", "output2Mask", "uuid", "updatedAt", "contentHash", "editorName" FROM "temporary_Song"`);
        await queryRunner.query(`DROP TABLE "temporary_Song"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_song_uuid" ON "Song" ("uuid") WHERE uuid IS NOT NULL`);
        await queryRunner.query(`ALTER TABLE "CoilEvent" RENAME TO "temporary_CoilEvent"`);
        await queryRunner.query(`CREATE TABLE "CoilEvent" ("id" integer PRIMARY KEY, "song_id" integer NOT NULL, "coilIndex" integer NOT NULL, "atMs" integer NOT NULL, "param" text NOT NULL, "value" real NOT NULL, CONSTRAINT "FK_8b7f3f0567e0c3f80bb83513218" FOREIGN KEY ("song_id") REFERENCES "Song" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "CoilEvent"("id", "song_id", "coilIndex", "atMs", "param", "value") SELECT "id", "song_id", "coilIndex", "atMs", "param", "value" FROM "temporary_CoilEvent"`);
        await queryRunner.query(`DROP TABLE "temporary_CoilEvent"`);
        await queryRunner.query(`ALTER TABLE "PlaylistSong" RENAME TO "temporary_PlaylistSong"`);
        await queryRunner.query(`CREATE TABLE "PlaylistSong" ("id" integer PRIMARY KEY, "idx" integer, "playlist_id" integer, "song_id" integer, CONSTRAINT "FK_278a7c559779bc80e9bdb732ed0" FOREIGN KEY ("song_id") REFERENCES "Song" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_88fd2840d87fbbf507316f08a8d" FOREIGN KEY ("playlist_id") REFERENCES "Playlist" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "PlaylistSong"("id", "idx", "playlist_id", "song_id") SELECT "id", "idx", "playlist_id", "song_id" FROM "temporary_PlaylistSong"`);
        await queryRunner.query(`DROP TABLE "temporary_PlaylistSong"`);
    }

}
